[versions]
mockk = "1.14.6"
kotlin = "2.2.21"
compose-compiler = "1.4.7"
compose-bom = "2025.11.01"
lifecycle-compose = "2.10.0"
navigation-compose = "2.9.6"
accompanist-systemuicontroller = "0.36.0"
junit-android = "1.3.0"
espresso-core = "3.7.0"
core-ktx = "1.17.0"
lifecycle = "2.10.0"
activity-compose = "1.12.0"
dagger = "2.57.2"
coroutines = "1.10.2"
junit = "4.13.2"
testng = "7.11.0"
mockk-jvm-agent = "1.14.6"
instrumental-test = "1.7.0"
test-runner = "1.7.0"
junit-ktx = "1.3.0"
coil = "2.7.0"
datastore = "1.2.0"
room = "2.8.4"
appcompat = "1.7.1"
admob = "24.8.0"
media3 = "1.8.0"
camerax = "1.5.1"
material-dialogs = "0.9.0"
kotlin-serialization = "1.9.0"
immutable-collections = "0.4.0"
firebase-bom = "34.6.0"
firebase-crashlytics-gradle = "2.9.5"
google-services = "4.3.15"
lottie = "6.7.1"
mlkit-language-id = "17.0.6"
mlkit-translate = "17.0.3"
zip4j = "2.11.5"
billing = "8.1.0"
ktor = "3.3.3"
workmanager = "2.11.0"
android-gradle-plugin = "8.13.1"
google-services-plugin = "4.4.4"
firebase-crashlytics-plugin = "3.0.6"
ksp = "2.2.21-2.0.4"
composePlugin = "2.2.21"
minSdk = "23"
targetSdk = "36"
minifyEnabledRelease = "true"
minifyEnabledDebug = "false"
javaCompatibilityVersion = "VERSION_17"
jvmTarget = "17"
packageName = "com.xxmrk888ytxx.mydictionary"


[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "junit-android" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testng = { module = "org.testng:testng", version.ref = "testng" }
mockk-jvm-agent = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk-jvm-agent" }

instrumental-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "instrumental-test" }
instrumental-test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
instrumental-test-core = { module = "androidx.test:core", version.ref = "instrumental-test" }
instrumental-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ktx" }
instrumental-test-rules = { module = "androidx.test:rules", version.ref = "instrumental-test" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }

admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admob" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

camerax-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-video = { module = "androidx.camera:camera-video", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
camerax-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax" }

material-dialogs-datetime = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "material-dialogs" }

kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutable-collections" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

mlkit-language-id = { module = "com.google.mlkit:language-id", version.ref = "mlkit-language-id" }
mlkit-translate = { module = "com.google.mlkit:translate", version.ref = "mlkit-translate" }

zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
workmanager-testing = { module = "androidx.work:work-testing", version.ref = "workmanager" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "19.4.4" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version = "22.5.0" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin" }
room = { id = "androidx.room", version.ref = "room" }

